### ISSUE TITLE
A question about croping images by timestamps

### ISSUE THREAD

**Issue by marco-hmc** [google-research-datasets/eev#1]
Hi there,
Thanks for your excellent work. I was trying to crop the image using the timestamps provided by the file. According to the dataset, there should be 3898 frames in the first video. But I got 3899 frames with the speed of 1/6 seconds instead. And here is my code.

**Comment by marco-hmc** [comment]
[videoLinkIsHere](https://www.youtube.com/watch?v=--fcq9ziOpE)

------
import cv2
import os

base_path = 'D:\marco\dataset\EVV\example\ITriedToBeHomelessForAWeekAndThisisWhatHappened'
file_path = base_path + '\I Tried To Be Homeless For A Week (And This is What Happened).mp4'
timestamp = 1.0/6.0

print('file_path=', file_path)
vidcap = cv2.VideoCapture(file_path)
count = 0
vidcap.set(cv2.CAP_PROP_POS_MSEC, timestamp * 1000 * count)
success, image = vidcap.read()

while success:
&nbsp; count += 1
&nbsp; if os.path.exists(os.path.join(base_path, 'imgs') is False:
&nbsp;&nbsp; os.mkidr(os.path.join(base_path, 'imgs'))
&nbsp; cv2.imwrite(os.path.join(base_path, 'imgs', str(count) + '.jpg'), image)
&nbsp; vidcap.set(cv2.CAP_PROP_POS_MSEC, timestamp * 1000 * count)
&nbsp; success, image = vidcap.read()

**Comment by jenjsun** [comment]
Hello and thanks for your interest! I think you can ignore the extra frame, as long as the frame timestamps you are using match the timestamps in the dataset.

**Comment by jenjsun** [comment]
Closed due to inactivity.
